GPIO_DOOROPEN = 23
GPIO_DOORCLOSED = 24
GPIO_INPUT_DEFAULT = 1

GPIO_TRIGGER = 6

MQTT_BROKER = "172.28.0.129"
MQTT_BROKERPORT = 1883

MQTT_CMD_TRIGGER = "homeassistant/cover/garagedoor/set"
MQTT_CMD_AVAILABILITY = "homeassistant/cover/garagedoor/available"
MQTT_CMD_STATUS = "homeassistant/cover/garagedoor"

MQTT_PAYLOAD_TRIGGERCMD_OPEN = b"OPEN"
MQTT_PAYLOAD_TRIGGERCMD_CLOSE = b"CLOSE"
MQTT_PAYLOAD_TRIGGERCMD_STOP = b"STOP"

MQTT_STATUS = [
    b"CLOSED",  # Confirmed CLOSED by GPIO_DOORCLOSED
    b"OPENING", # Received a trigger if GPIO_DOORCLOSED or STOPPED_WHILE_CLOSING
    b"STOPPED", # Received a trigger when MQTT_STATUS was "Opening" (STOPPED_WHILE_OPENING)
    b"UNKNOWN", # Received a trigger when MQTT_STATUS was unknown
    b"CLOSING", # Received a trigger if GPIO_DOOROPEN or STOPPED_WHILE_OPENING
    b"STOPPED", # Received a trigger when MQTT_STATUS was "Closing" (STOPPED_WHILE_CLOSING)
    b"OPEN"     # Confirmed OPEN by GPIO_DOOROPEN
]

MQQT_PAYLOAD_AVAILABLE = "online"
MQQT_PAYLOAD_NOT_AVAILABLE = "offline"

# Non-configurable constants
DOORSTATE_CLOSED = 0
DOORSTATE_OPENING = 1
DOORSTATE_STOPPED_WHILE_OPENING = 2
DOORSTATE_UNKNOWN = 3
DOORSTATE_CLOSING = 4
DOORSTATE_STOPPED_WHILE_CLOSING = 5
DOORSTATE_OPEN = 6
